package com.Nook.backend.auth;

import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
public class EmailService {

    private final JavaMailSender mailSender;

    @Value("${app.frontend.url}")
    private String frontendUrl;

    // ── Password reset ────────────────────────────────────────────────────────

    public void sendPasswordResetEmail(String to, String token) {
        String url = frontendUrl + "/reset-password?token=" + token;
        send(to,
                "Nook – Password Reset Request",
                "Click the link below to reset your password. It expires in 15 minutes:\n\n" + url);
    }

    // ── Magic link ────────────────────────────────────────────────────────────

    public void sendMagicLinkEmail(String to, String token) {
        String url = frontendUrl + "/magic-login?token=" + token;
        send(to,
                "Nook – Your Magic Login Link",
                "Click the link below to log in instantly. It expires in 15 minutes:\n\n" + url);
    }

    // ── Email OTP (step 2 of 3FA) ─────────────────────────────────────────────

    /**
     * Sends a 6-digit one-time code as part of the three-factor login flow.
     * The code is generated by AuthService and stored (hashed) on the User.
     */
    public void sendOtpEmail(String to, String code) {
        send(to,
                "Nook – Your Login Code",
                "Your one-time login code is:\n\n" + code + "\n\nIt expires in 5 minutes. " +
                        "Do not share this code with anyone.");
    }

    // ── Internal helper ───────────────────────────────────────────────────────

    private void send(String to, String subject, String body) {
        SimpleMailMessage msg = new SimpleMailMessage();
        msg.setTo(to);
        msg.setSubject(subject);
        msg.setText(body);
        msg.setFrom("noreply@nook.com");
        mailSender.send(msg);
    }
}