spring.application.name=backend
spring.profiles.active=v1
server.port=8080

jwt.secret=nook-super-secret-key-change-this-in-production-please
# login token lasts 24 hours
jwt.expiration-ms=86400000
spring.autoconfigure.exclude=org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
spring.graphql.graphiql.enabled=true