spring.application.name=backend
spring.profiles.active=v2
server.port=8080
server.address=0.0.0.0

jwt.secret=nook-super-secret-key-change-this-in-production-please
# login token lasts 24 hours
jwt.expiration-ms=86400000
spring.graphql.graphiql.enabled=true


spring.datasource.url=jdbc:postgresql://localhost:5432/nook
spring.datasource.username=postgres
spring.datasource.password=scapa-ma

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect